---
title: "DT"
output: html_document
date: "2023-03-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#install.packages("rpart")
#install.packages("rattle")
#install.packages("rpart.plot")
#install.packages("RColorBrewer")
#install.packages("Cairo")
#install.packages("network")
library(rpart)   ## FOR Decision Trees
library(rattle)  ## FOR Decision Tree Vis
library(rpart.plot)
library(RColorBrewer)
#library(Cairo)
library(network)
library(ggplot2)
#install.packages("wordcloud")
library(wordcloud)
#install.packages("tm")

library(slam)
#install.packages("quanteda")
library(quanteda)
library(SnowballC)
library(proxy)
#install.packages("stringr")
library(stringr)
#install.packages("textmineR")
library(textmineR)
library(igraph)
#install.packages("caret")
library(caret)
library(MASS) 
library(reshape2) 
library(reshape) 
# Loading dataset
Myfile1= "/Users/yaminipriyankakandikattu/Desktop/AH_Monthly_Provisional_Counts_of_Deaths_for_Select_Causes_of_Death_by_Sex__Age__and_Race_and_Hispanic_Origin.csv"
df <- read.csv(Myfile1,stringsAsFactors=TRUE)
colnames(df)
df
head(df)
melt_data <- melt(df, id = c("AnalysisDate","Date.Of.Death.Year","Date.Of.Death.Month","Start.Date",
"End.Date","Jurisdiction.of.Occurrence","Sex","Race.Ethnicity","AgeGroup"))
melt_data
#melt_data[melt_data == 'F'] <- 'Female'
#melt_data[melt_data == 'M'] <- 'Male'
colnames(melt_data)
colnames(melt_data)[which(names(melt_data) == "variable")] <- "Causeofdeath"
colnames(melt_data)[which(names(melt_data) == "value")] <- "NoofDeaths"
data <- subset (melt_data, select = -c(AnalysisDate,Date.Of.Death.Year,Date.Of.Death.Month,Start.Date,End.Date,Jurisdiction.of.Occurrence))
data
is.na(data)
data = na.omit(data)
data
data = data[data$Causeofdeath != 'AllCause' & data$Causeofdeath != 'NaturalCause', ] 

#data = data[data$NoofDeaths != '0' & data$NoofDeaths != '0', ] 
colnames(data)
apply(data, 2, table)

GoPlot <- function(x) {
  
  G <-ggplot(data=data, aes(.data[[x]], y="") ) +
  geom_bar(stat="identity", aes(fill =.data[[x]])) 
  
  return(G)
}

## Use the function in lappy
lapply(names(data), function(x) GoPlot(x))


(DataSize=nrow(data)) ## how many rows?
(TrainingSet_Size<-floor(DataSize*(3/4))) ## Size for training set
(TestSet_Size <- DataSize - TrainingSet_Size) ## Size for testing set

set.seed(1234)

(MyTrainSample <- sample(nrow(data),
                                    TrainingSet_Size,replace=FALSE))
                                    
                                    
                                    ## ##Use the sample of row numbers to grab those rows only from
## the dataframe....
(MyTrainingSET <- data[MyTrainSample,])
table(MyTrainingSET$Sex)

## Training and Testing datasets MUST be disjoint. Why?
(MyTestSET <- data[-MyTrainSample,])
table(MyTestSET$Sex)

# Remove lables from test set

(TestKnownLabels <- MyTestSET$Sex)
(MyTestSET <- MyTestSET[ , -which(names(MyTestSET) %in% c("Sex"))])

MyTrainingSET
str(MyTrainingSET)

DT <- rpart(MyTrainingSET$Sex ~ ., data = MyTrainingSET, method="class")
summary(DT)
DT2<-rpart(MyTrainingSET$Sex ~ ., data = MyTrainingSET,cp=.01, method="class")
summary(DT2)
plotcp(DT)

DT3<-rpart(MyTrainingSET$Sex ~ ., 
           data = MyTrainingSET,cp=0.01, method="class",
           parms = list(split="information"),minsplit=4)
           
summary(DT3)

DT4<-rpart(MyTrainingSET$Sex ~ AgeGroup, 
           data = MyTrainingSET,cp=0, method="class",
           parms = list(split="information"),minsplit=4)
summary(DT4)           

DT5<-rpart(MyTrainingSET$Sex ~ Race.Ethnicity+AgeGroup, 
           data = MyTrainingSET,cp=0, method="class",
           parms = list(split="information"),minsplit=4)
summary(DT4)           
## DT---------------------------------
(DT_Prediction= predict(DT, MyTestSET, type="class"))
## Confusion Matrix
tab1<-table(DT_Prediction,TestKnownLabels)
confusionMatrix(tab1)
## one way to make a confu mat
## VIS..................
fancyRpartPlot(DT)

## DT2-----------------------------
### Example two with cp - a lower cp value is a bigger tree
(DT_Prediction2= predict(DT2, MyTestSET, type = "class"))
## ANother way to make a confusion matrix
caret::confusionMatrix(DT_Prediction2, TestKnownLabels, positive="true")
table(DT_Prediction2,TestKnownLabels)
fancyRpartPlot(DT2)
## Example three with information gain and lower cp

##DT3---------------------------------------------------------
(DT_Prediction3= predict(DT3, MyTestSET, type = "class"))
#confusionMatrix(DT_Prediction3, TestKnownLabels, positive="true")
table(DT_Prediction3,TestKnownLabels)
rattle::fancyRpartPlot(DT3,main="Decision Tree", cex=.5)
fancyRpartPlot(DT3)

##DT4---------------------------------------------------------
(DT_Prediction4= predict(DT4, MyTestSET, type = "class"))
confusionMatrix(DT_Prediction4, TestKnownLabels, positive="true")
table(DT_Prediction4,TestKnownLabels)
rattle::fancyRpartPlot(DT4,main="Decision Tree", cex=.5)
fancyRpartPlot(DT4)
##DT5______________________________________________________
(DT_Prediction5= predict(DT5, MyTestSET, type = "class"))
confusionMatrix(DT_Prediction5, TestKnownLabels, positive="true")
tab1=table(DT_Prediction5,TestKnownLabels)
confusionMatrix(tab1)
rattle::fancyRpartPlot(DT5,main="Decision Tree", cex=.4)
fancyRpartPlot(DT5)